routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Designs
Route::resource('design', 'DesignController');


Route::post('/image/upload', 'ImageController@upload')->name('image.upload');

app/Models/Design.php
<?php

namespace App\Models;

use App\Models\Traits\Imageable;

class Design extends Model
{
    use Imageable;

    public $fillable = [
        'internal_id',
        'name',
        'preview_url',
    ];
}

app/Models/Image.php
<?php

namespace App\Models;

use Storage;

class Image extends Model
{
    public $fillable = [
        'src',
        'alt'
    ];

    public function getUrlAttribute()
    {
        return Storage::url($this->src);
    }
}

app/Models/Model.php
<?php

namespace App\Models;

class Model extends \Illuminate\Database\Eloquent\Model
{

}

app/Models/Traits/Imageable.php
<?php

namespace App\Models\Traits;

use App\Models\Image;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use InvalidArgumentException;

trait Imageable
{
    public function getDefaultImageUrl()
    {
        if (!($image = $this->getDefaultImage())) {
            return null;
        }
        return $image->url;
    }

    public function getDefaultImage()
    {
        return $this->images()->first();
    }

    public function images(): MorphToMany
    {
        return $this->morphToMany(Image::class, 'imageable');
    }

    public function addStorageFile($src, $alt = null)
    {
        $image = Image::firstOrNew(compact('src'));
        if (!$image->exists) {
            $image->fill(compact('src', 'alt'))->save();
        }
        $this->addImage($image);
    }

    public function addImage(Image $image): void
    {
        $this->images()->attach($image);
    }

    public function addImages(iterable $images)
    {
        foreach ($images as $image) {
            if (!$image instanceof Image) {
                throw new InvalidArgumentException(
                    sprintf(
                        'Every element passed to addImages must be a Image object. Given `%s`.',
                        is_object($image) ? get_class($image) : gettype($image)
                    )
                );
            }
        }

        return $this->images()->saveMany($images);
    }

    public function removeImage(Image $image)
    {
        return $this->images()->detach($image);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DesignController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DesignDestroyRequest;
use App\Http\Requests\DesignEditRequest;
use App\Http\Requests\DesignStoreRequest;
use App\Http\Requests\DesignUpdateRequest;
use App\Models\Design;
use Exception;

class DesignController extends Controller
{
    public function show(Design $design)
    {
        throw new Exception('not implemented');
    }

    public function index()
    {
        return view('design.index', [
            'designs' => Design::with('images')->paginate()
        ]);
    }

    public function create()
    {
        return view('design.create-edit', ['design' => null]);
    }

    public function store(DesignStoreRequest $request)
    {
        $design = Design::create($request->only(['internal_id', 'name', 'preview_url']));
        $design->images()->sync($request->input('images', []));
        return redirect()->route('design.edit', $design)->withMessage('Design successfully created');
    }

    public function edit(DesignEditRequest $request, Design $design)
    {
        return view('design.create-edit', compact('design'));
    }

    public function update(DesignUpdateRequest $request, Design $design)
    {
        $design
            ->fill($request->only(['internal_id', 'name', 'preview_url']))
            ->save();
        $design->images()->sync($request->input('images', []));
        return redirect()->back()->withMessage('Design successfully saved');
    }

    public function destroy(DesignDestroyRequest $request, Design $design)
    {
        if ($design->delete()) {
            return redirect()->route('design.index')->with('message', 'Design #'.$design->id.' successfully destroyed');
        }

        return redirect()->route('design.index')->withErrors(['Something gone wrong']);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UploadImageRequest;
use App\Models\Image;

class ImageController extends Controller
{
    public function upload(UploadImageRequest $request)
    {
        $upload = $request->file('file')->store('images', 'public');
        $image = Image::create([
            'src' => $upload,
        ]);
        return [
            'success' => true,
            'id' => $image->id,
        ];
    }
}

resources/views/design/create-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="mb-4">
                    <a href="{{ route('design.index') }}">&lt; all designs</a>
                    Design {{ $design ? 'editing' : 'creation' }}
                </h2>
            </div>
            <div class="col text-right">
                @if($design)
                    <form method="post" action="{{ route('design.destroy', $design) }}" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <input type="submit" class="btn btn-danger" value="Delete"/>
                    </form>
                @endif
                <input type="submit" form="mainForm" class="btn btn-primary" value="Save"/>
            </div>
        </div>

        <form id="mainForm" method="post" action="{{ $design ? route('design.update', $design) : route('design.store') }}">
            @csrf
            @if($design) @method('PATCH') @endif

            <div class="row">
                <div class="col-2">
                    <input type="text" class="form-control" placeholder="ID" name="internal_id"
                           value="{{ old('internal_id', $design->internal_id ?? '') }}"/>
                </div>
                <div class="col-5">
                    <input type="text" class="form-control" placeholder="Name" name="name"
                           value="{{ old('name', $design->name ?? '') }}"/>
                </div>
                <div class="col-5">
                    <input type="text" class="form-control" placeholder="Preview URL" name="preview_url"
                           value="{{ old('preview_url', $design->preview_url ?? '') }}"/>
                </div>
            </div>

            <div class="row mt-3">
                <div class="col-12">
                    <image-uploader :images="{{ $design ? $design->images->map(fn($e)=>$e->only(['id', 'src', 'url'])) : '{}' }}"/>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/design/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="mb-4">all designs</h2>
            </div>
            <div class="col text-right">
                <a href="{{ route('design.create') }}" class="btn btn-primary">
                    Create new
                </a>
            </div>
        </div>

        <div class="text-decoration-none d-flex flex-wrap justify-content-between">
            @foreach($designs as $design)
                <a href="{{ route('design.edit', $design) }}" class="mb-5 scale-1-hover text-decoration-none transition-default z-index-1000">
                    <div style="min-width: 200px; min-height: 300px;">
                        @if($image = $design->images->first())
                            <img class="rounded" width="200" height="300" style="object-fit: cover" src="{{ $image->url }}" alt="{{ $image->alt }}"/>
                        @endif
                    </div>
                    <div class="mt-3">
                        <div class="align-middle badge rounded-pill pl-2 pr-2 badge badge-primary d-inline">{{ $design->internal_id }}</div>
                        <div class="align-middle d-inline font-weight-bold ml-1 fs-2">{{ $design->name }}</div>
                    </div>
                </a>
            @endforeach
        </div>
        <div class="d-flex justify-content-center">
            {{ $designs->links() }}
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        You are logged in!
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    @stack('js')
    <script src="{{ mix('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Styles -->
    @stack('css')
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @if(session('message') || $errors->any())
            <div class="container mt-2">
                <div class="row">
                    <div class="col">
                        @if(session('message'))
                            <div class="alert alert-success">
                                {{ session('message') }}
                            </div>
                        @endif

                        @if($errors->any())
                            @foreach($errors->all() as $error)
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
        @endif

        @yield('content')
    </main>
</div>
</body>
</html>